buscar todas las empresas que empiecen con un string
MoyaRamiro/api pull request #6
Opened 2023-11-30 18:01 UTC by MoyaRamiro

2023-11-30 19:22 UTC, MoyaF requested changes

2023-11-30 19:22 UTC, MoyaF commented on src/main/java/moyitaEmpress/empresas/EmpresaRepository.java
> +    public List<Empresa> buscarEmpresa(String buscado) {
¿Como llamas a este método desde un cliente HTTP?

2023-12-01 03:39 UTC, MoyaRamiro commented on src/main/java/moyitaEmpress/empresas/EmpresaRepository.java
> +    public List<Empresa> buscarEmpresa(String buscado) {
nose

2023-12-01 20:05 UTC, MoyaF commented on src/main/java/moyitaEmpress/empresas/EmpresaRepository.java
> +    public List<Empresa> buscarEmpresa(String buscado) {
No estás exponiendo ningún endpoint

2023-12-02 20:04 UTC, merged